### ISSUE TITLE
Can't install for python 3.12.4

### ISSUE THREAD

**Issue by deafmute1** [lucasvanmol/latex-ocr-server#3]
pytorch 2.1.0 cannot be installed against latest python, 3.12.4.

```
ERROR: Could not find a version that satisfies the requirement torch~=2.1.0 (from latex-ocr-server) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
ERROR: No matching distribution found for torch~=2.1.0
```

Potential workaround with pipx:
`pipx install latex-ocr-server --python <path to an older python binary>` 

However, because latex_ocr_sever does not install itself as a stanadalone binary, I'm not sure how to get this working. I used `/opt/homebrew/bin/python3.11` as my python binary instead of and the install seemed to work fine, but `/opt/homebrew/bin/python3.11 -m latex_ocr_server --version` returns no module - presumably due to some environmental mismatch with using a non default binary?

**Comment by Jboltle** [comment]
Having the same issue, I just used hugging face, but the latency is unBearable.

**Comment by lucasvanmol** [comment]
Thanks for raising this issue, you should be able to install version 0.1.1 with Python 3.12!
